name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install node dependencies
      run: |
        cd ui
        npm install

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: Install go-bindata
      run: |
        cd api
        go get -u github.com/go-bindata/go-bindata/...
        cd $GOPATH/src/github.com/go-bindata/go-bindata
        go build
        go-bindata -version
        sudo copy go-bindata /bin

    - name: build
      run:  make build

