name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install node dependencies
      run: cd ui; npm install

    - name: Install go commands
      run: cd api; go get -u github.com/go-bindata/go-bindata/...

    - name: Build image
      run: make build
