name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install node dependencies
      run: |
        cd ui
        npm install

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: Install go-bindata and swag
      run: |
        go install github.com/go-bindata/go-bindata/go-bindata@latest
        go install github.com/swaggo/swag/cmd/swag@latest
        export PATH=$(go env GOPATH)/bin:$PATH

    - name: Build
      run:  make build

